- name: Wipe Kubernetes, Docker, and Podman
  hosts: all
  become: true
  tasks:

    - name: Remove Kubernetes-related packages
      package:
        name:
          - kubeadm
          - kubelet
          - kubectl
          - kubernetes-cni
        state: absent
      ignore_errors: true

    - name: Remove Docker-related packages
      package:
        name:
          - docker
          - docker-ce
          - docker-ce-cli
          - docker-engine
          - containerd.io
          - docker-compose-plugin
        state: absent
      ignore_errors: true

    - name: Remove Podman-related packages
      package:
        name:
          - podman
          - buildah
        state: absent
      ignore_errors: true

    - name: Remove container and Kubernetes files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/longhorn
        - /export/longhorn
        - /mnt/longhorn
        - /etc/docker
        - /var/lib/containerd
        - /var/lib/kubelet
        - /etc/systemd/system/kubelet.service.d
        - /etc/systemd/system/docker.service.d
        - /usr/local/bin/cri-dockerd
        - /etc/systemd/system/cri-docker.service
        - /etc/systemd/system/cri-docker.socket
        - /etc/cni
        - /opt/cni
        - /var/lib/etcd
        - /root/.kube
        - /home/*/.kube
        - /export/home/*/.kube
        - /var/lib/podman
        - /run/podman
        - /run/containerd

    # As /var/lib/docker is mounted, so I can add it in above list. I added a patch here.
    - name: Remove all contents under /var/lib/docker
      shell: rm -rf /var/lib/docker/*
      args:
        warn: false
      ignore_errors: true

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Remove leftover container runtime socket files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /run/docker.sock
        - /run/cri-dockerd.sock
        - /run/containerd/containerd.sock
        - /run/podman/podman.sock

    - name: Remove leftover users
      user:
        name: "{{ item }}"
        state: absent
        remove: yes
      loop:
        - docker
        - containerd
        - kube

    - name: Remove leftover groups
      group:
        name: "{{ item }}"
        state: absent
      loop:
        - docker
        - containerd
        - kube