---
- name: Check Kubernetes binary versions and paths across hosts
  hosts: all
  gather_facts: false
  vars:
    binaries:
      - name: kubelet
        version_cmd: "kubelet --version"
        path_candidates:
          - /usr/bin/kubelet
          - /usr/local/bin/kubelet
      - name: kubeadm
        version_cmd: "kubeadm version -o short"
        path_candidates:
          - /usr/bin/kubeadm
          - /usr/local/bin/kubeadm
      - name: kubectl
        version_cmd: "kubectl version --client -o json | jq -r .clientVersion.gitVersion"
        path_candidates:
          - /usr/bin/kubectl
          - /usr/local/bin/kubectl

  tasks:
    - name: Find binary actual paths
      shell: |
        for p in {{ item.path_candidates | join(' ') }}; do
          if [ -x "$p" ]; then
            echo "$p"
            exit 0
          fi
        done
        exit 1
      register: resolved_paths
      loop: "{{ binaries }}"
      loop_control:
        label: "{{ item.name }}"
      changed_when: false
      failed_when: false

    - name: Run version command for each resolved binary
      shell: "{{ item.version_cmd }}"
      register: version_output
      loop: "{{ binaries }}"
      when: resolved_paths.results[loop.index0].rc == 0
      loop_control:
        label: "{{ item.name }}"
      changed_when: false
      failed_when: false

    - name: Print summary
      debug:
        msg: |
          {{ item.name }}:
            Path: {{ resolved_paths.results[loop.index0].stdout | default('Not found') }}
            Version: {{ version_output.results[loop.index0].stdout | default('Unknown') }}
      loop: "{{ binaries }}"
      loop_control:
        label: "{{ item.name }}"
