- name: Get Kubeadm join command for worker nodes
  hosts: host2
  become: true
  tasks:

    - name: Generate join command for workers
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set worker join command for other plays
      add_host:
        name: kube_worker_join
        kubeadm_join_command: "{{ join_command_raw.stdout }}"

- name: Join worker nodes to the Kubernetes cluster
  hosts: workers
  become: true
  vars:
    kubeadm_join_command: "{{ hostvars['kube_worker_join']['kubeadm_join_command'] }}"
  tasks:

    - name: Join the node to the Kubernetes cluster
      command: "{{ kubeadm_join_command }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
