- name: Install Kubernetes dependencies
  hosts: all
  become: true
  tasks:

    - name: Disable swap (temporary)
      command: swapoff -a

    - name: Disable swap (permanently)
      replace:
        path: /etc/fstab
        regexp: '^([^#].*[\s\t]swap[\s\t].*)$'
        replace: '# \1'

    - name: Enable required kernel modules
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter

    - name: Load kernel modules now
      shell: |
        modprobe overlay
        modprobe br_netfilter

    - name: Set sysctl params
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1

    - name: Apply sysctl changes
      command: sysctl --system

    - name: Install required packages
      dnf:
        name:
          - curl
          - gnupg
          - ca-certificates
          - yum-utils
          - iproute-tc
        state: present

    - name: Add Kubernetes repo
      yum_repository:
        name: kubernetes
        description: Kubernetes YUM Repository
        baseurl: https://pkgs.k8s.io/core:/stable:/v1.32/rpm/
        enabled: 1
        gpgcheck: 1
        gpgkey: https://pkgs.k8s.io/core:/stable:/v1.32/rpm/repodata/repomd.xml.key

    - name: Ensure dnf-plugins-core is installed
      dnf:
        name: dnf-plugins-core
        state: present

    - name: Add Docker CE repository using config-manager
      command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install Kubernetes required packages
      dnf:
        name:
          - kubelet # agent that runs on each node
          - kubeadm # tool to bootstrap the cluster
          - kubectl # CLI to interact with the cluster (only required on master/admin host)
          - containerd.io # container runtime (preferred to CRI-O or Docker)
        state: present
        update_cache: yes

    - name: Reload systemd daemon
      command: systemctl daemon-reexec
      ignore_errors: true

    - name: Reload systemd daemon
      command: systemctl daemon-reload
      ignore_errors: true

    - name: Generate default containerd config
      command: containerd config default > /etc/containerd/config.toml

    - name: Comment out any line containing disabled_plugins
      lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^\s*disabled_plugins.*'
        line: '# \g<0>'
        backrefs: yes

    - name: Enable SystemdCgroup in containerd
      replace:
        path: /etc/containerd/config.toml
        regexp: '^(\s*SystemdCgroup\s*=\s*)false'
        replace: '\1true'

    - name: Restart and enable containerd
      systemd:
        name: containerd
        state: restarted
        enabled: true

    - name: Enable kubelet
      systemd:
        name: kubelet
        enabled: true
        state: stopped

    - name: Download Helm install script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0755'

    - name: Run Helm install script
      command: /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm

    - name: Verify Helm is installed
      command: helm version
      register: helm_version
      changed_when: false

- name: Install special Kubernetes dependencies for master hosts
  hosts: masters
  become: true
  tasks:

    - name: Install kubectl for master hosts
      dnf:
        name:
          - kubectl # CLI to interact with the cluster (only required on master/admin host)
        state: present
        update_cache: yes