- name: Full Cleanup of Kubernetes, Container Runtimes, Calico, and Rancher
  hosts: all
  become: true
  tasks:

    - name: Stop all running Docker containers
      shell: docker ps -q | xargs -r docker stop
      args: { warn: false }
      ignore_errors: true

    - name: Remove all Docker containers
      shell: docker ps -aq | xargs -r docker rm -f
      args: { warn: false }
      ignore_errors: true

    - name: Stop all running Podman containers
      shell: podman ps -q | xargs -r podman stop
      args: { warn: false }
      ignore_errors: true

    - name: Remove all Podman containers
      shell: podman ps -aq | xargs -r podman rm -f
      args: { warn: false }
      ignore_errors: true

    - name: Stop all containerd containers (if nerdctl is available)
      shell: |
        if command -v nerdctl >/dev/null 2>&1; then
          nerdctl ps -q | xargs -r nerdctl stop
          nerdctl ps -aq | xargs -r nerdctl rm -f
        fi
      args:
        executable: /bin/bash
      ignore_errors: true

    - name: Reset kubeadm cluster (if applicable)
      shell: kubeadm reset -f
      ignore_errors: true

    - name: Stop and disable related services
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
        masked: true
      loop:
        - kubelet
        - docker
        - podman
        - containerd
        - cri-o
        - cri-dockerd
        - calico-node
        - calico-felix
        - calico-bird
        - rancher
      ignore_errors: true

    - name: Kill any remaining cri-dockerd processes
      shell: |
        pkill -f cri-dockerd || true
      args:
        warn: false
      ignore_errors: true

    - name: Flush all iptables rules (use with caution)
      shell: |
        iptables -F
        iptables -t nat -F
        iptables -t mangle -F
        iptables -X
      args: { warn: false }
      ignore_errors: true

    - name: Reload systemd daemon
      command: systemctl daemon-reexec
      ignore_errors: true

    - name: Reload systemd daemon
      command: systemctl daemon-reload
      ignore_errors: true
