- name: Wipe Kubernetes, Docker, Podman, and all related data
  hosts: all
  become: true
  tasks:

    - name: Remove Kubernetes-related packages
      package:
        name:
          - kubeadm
          - kubelet
          - kubectl
          - kubernetes-cni
        state: absent
      ignore_errors: true

    - name: Remove Docker-related packages
      package:
        name:
          - docker
          - docker-ce
          - docker-ce-cli
          - docker-engine
          - containerd.io
          - docker-compose-plugin
        state: absent
      ignore_errors: true

    - name: Remove Podman-related packages
      package:
        name:
          - podman
          - buildah
        state: absent
      ignore_errors: true

    - name: Remove container and Kubernetes-related files and directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/longhorn
        - /export/longhorn
        - /mnt/longhorn
        - /opt/cni
        - /etc/cni
        - /etc/docker
        - /etc/containerd
        - /var/lib/etcd
        - /var/lib/containerd
        - /var/lib/kubelet
        - /var/lib/podman
        - /usr/local/bin/cri-dockerd
        - /root/.kube
        - /run/podman
        - /run/containerd
        - /etc/systemd/system/kubelet.service.d
        - /etc/systemd/system/docker.service.d
        - /etc/systemd/system/cri-docker.service
        - /etc/systemd/system/cri-docker.socket
        - /etc/systemd/system/containerd.service
        - /usr/local/lib/systemd/system/kubelet.service.d
        - /usr/local/lib/systemd/system/docker.service.d
        - /usr/local/lib/systemd/system/cri-docker.service
        - /usr/local/lib/systemd/system/cri-docker.socket
        - /usr/local/lib/systemd/system/containerd.service
      ignore_errors: true

    - name: Remove user .kube directories from all home paths
      shell: |
        for d in /home/* /export/home/*; do
          [ -d "$d/.kube" ] && rm -rf "$d/.kube"
        done
      args:
        executable: /bin/bash
      ignore_errors: true

    - name: Remove contents of /var/lib/docker (mounted directory)
      shell: rm -rf /var/lib/docker/*
      args:
        warn: false
      ignore_errors: true

    - name: Remove leftover container runtime socket files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /run/docker.sock
        - /run/cri-dockerd.sock
        - /run/containerd/containerd.sock
        - /run/podman/podman.sock
      ignore_errors: true

    - name: Reload systemd daemon
      command: systemctl daemon-reload
      ignore_errors: true

    - name: Remove leftover system users
      user:
        name: "{{ item }}"
        state: absent
        remove: yes
      loop:
        - docker
        - containerd
        - kube
      ignore_errors: true

    - name: Remove leftover system groups
      group:
        name: "{{ item }}"
        state: absent
      loop:
        - docker
        - containerd
        - kube
      ignore_errors: true
