- name: Wipe Kubernetes, Docker, Podman, and all related data
  hosts: all
  become: true
  tasks:

    - name: Remove Kubernetes-related packages
      package:
        name:
          - kubeadm
          - kubelet
          - kubectl
          - kubernetes-cni
        state: absent
      ignore_errors: true

    - name: Remove Docker-related packages
      package:
        name:
          - docker
          - docker-ce
          - docker-ce-cli
          - docker-engine
          - containerd.io
          - docker-compose-plugin
        state: absent
      ignore_errors: true

    - name: Remove Podman-related packages
      package:
        name:
          - podman
          - buildah
        state: absent
      ignore_errors: true

    - name: Remove container and Kubernetes-related files and directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /opt/docker
        - /etc/docker
        - /var/log/docker.log
        - /run/docker.sock
        - /etc/systemd/system/docker.service.d
        - /usr/local/lib/systemd/system/docker.service.d
        - /etc/systemd/system/multi-user.target.wants/docker.service

        - /var/lib/podman
        - /run/podman
        - /run/podman/podman.sock
        - /var/log/podman.log

        - /run/k3s
        - /etc/rancher/k3s
        - /usr/bin/k3s
        - /usr/local/bin/k3s
        - /etc/systemd/system/k3s.service
        - /etc/systemd/system/k3s-agent.service
        - /run/flannel

        - /etc/containerd
        - /var/lib/containerd
        - /run/containerd
        - /run/containerd/containerd.sock
        - /opt/containerd
        - /etc/systemd/system/containerd.service
        - /usr/local/lib/systemd/system/containerd.service
        - /usr/local/bin/containerd*
        - /usr/local/bin/nerdctl
        - /usr/bin/containerd*

        - /var/lib/cri-dockerd
        - /opt/cri-dockerd
        - /usr/bin/cri-dockerd
        - /usr/local/bin/cri-dockerd
        - /run/cri-dockerd.sock
        - /etc/systemd/system/cri-docker.service
        - /etc/systemd/system/cri-docker.socket
        - /usr/local/lib/systemd/system/cri-docker.service
        - /usr/local/lib/systemd/system/cri-docker.socket

        - /etc/rancher
        - /var/lib/rancher
        - /var/log/rancher
        - /usr/bin/rancher
        - /usr/local/bin/rancher
        - /usr/lib/systemd/system/rancher.service

        - /etc/kubernetes
        - /etc/kubelet
        - /etc/sysconfig/kubelet
        - /var/lib/kubelet
        - /var/lib/etcd
        - /etc/systemd/system/kubelet.service.d
        - /usr/local/lib/systemd/system/kubelet.service.d
        - /etc/systemd/system/multi-user.target.wants/kubelet.service
        - /home/*/.kube
        - /root/.kube
        - /export/home/*/.kube
        - /usr/bin/kube*
        - /var/log/pods
        - /var/log/containers
        - /var/log/kubelet.log

        - /var/lib/longhorn
        - /mnt/longhorn
        - /export/longhorn

        - /opt/cni
        - /etc/cni
        - /var/lib/cni

        - /etc/calico
        - /var/lib/calico
        - /var/run/calico
        - /var/log/calico

        - /mnt/k8sMount
        - /var/log/etcd.log
      ignore_errors: true

    # As /var/lib/docker is mounted
    - name: Remove contents of /var/lib/docker (mounted directory)
      shell: rm -rf /var/lib/docker/*
      args:
        warn: false
      ignore_errors: true

    - name: Remove user .kube directories from all home paths
      shell: |
        for d in /home/* /export/home/*; do
          [ -d "$d/.kube" ] && rm -rf "$d/.kube"
        done
      args:
        executable: /bin/bash
      ignore_errors: true

    - name: Reload systemd daemon
      command: systemctl daemon-reexec
      ignore_errors: true

    - name: Reload systemd daemon
      command: systemctl daemon-reload
      ignore_errors: true

    - name: Remove leftover users
      user:
        name: "{{ item }}"
        state: absent
        remove: yes
      loop:
        - docker
        - containerd
        - kube
        - rancher
      ignore_errors: true

    - name: Remove leftover groups
      group:
        name: "{{ item }}"
        state: absent
      loop:
        - docker
        - containerd
        - kube
        - rancher
      ignore_errors: true
