// extra properties for sharing configuration across configuration blocks
extra["javaVersion"] = libs.versions.java.get()

// apply plugins to the root project
plugins {
    java // turns a project into a standard Java module
    // adding tasks to compile Java source code, run tests, create JARs, etc.
    // defining source directories like src/main/java and src/test/java
    // create dependency configurations like implementation, api, testImplementation, etc.

    java-library // extends 'java' plugin for building Java libraries
    // adds features for consumers of the library, like api() configuration for dependencies

    alias(...) apply false // placeholders for plugin aliases from version catalog
}

// configuration for all projects
allprojects {
    group = "com.example"
    version = "1.0.0-SNAPSHOT"
}

// configuration for all subprojects (not including root project)
subprojects {
    apply(plugin = "java")

    java {

        toolchain {
            // you want Gradle to use a specific Java version for compiling your project, regardless of the system JDK.
            languageVersion.set(JavaLanguageVersion.of(rootProject.extra["javaVersion"].toString()))
        }

        // ensures only Java 17 features are allowed, even if compiling with Java 21.
        sourceCompatibility = JavaVersion.VERSION_17

        // ensures generated bytecode is compatible with Java 17 runtimes.
        targetCompatibility = JavaVersion.VERSION_17
    }

    // configure Java compilation tasks
    tasks.withType<JavaCompile> {
        // setting UTF-8 encoding ensures consistent handling of source files with non-ASCII characters across different systems and environments.
        // it is recommended if your codebase contains international characters, special symbols, or if you want to avoid platform-dependent encoding issues.
        options.encoding = "UTF-8"
    }

    tasks.withType<Test> {
        useJUnitPlatform()
    }
}
