---
- name: Clean Up Kubernetes Resources
  hosts: all
  become: true
  tasks:
    - name: Reset kubeadm
      command: kubeadm reset -f
      ignore_errors: true

    - name: Remove kubeadm, kubelet, kubectl if installed
      yum:
        name:
          - kubeadm
          - kubelet
          - kubectl
          - cri-tools
          - kubernetes-cni
        state: absent
        autoremove: yes

    - name: Remove containerd if installed
      yum:
        name:
          - containerd.io
        state: absent
        autoremove: yes
