---
- name: Pre-check tasks
  hosts: all
  become: true
  gather_facts: no

  tasks:
    # Check Firewall and Open Required Ports

    - name: Check if firewalld is installed
      shell: rpm -q firewalld
      register: firewalld_check
      ignore_errors: yes

    - name: Check if firewalld service is running
      shell: systemctl is-active firewalld
      register: firewalld_status
      ignore_errors: yes
      when: firewalld_check.rc == 0

    - name: Ensure required ports are open (only if firewall active)
      shell: |
        firewall-cmd --permanent --add-port=6443/tcp
        firewall-cmd --permanent --add-port=2379-2380/tcp
        firewall-cmd --permanent --add-port=10250-10252/tcp
        firewall-cmd --permanent --add-port=30000-32767/tcp
        firewall-cmd --reload
      when:
        - firewalld_check.rc == 0
        - firewalld_status.stdout == "active"

    - name: Verify that ports are open
      shell: firewall-cmd --list-ports
      register: opened_ports
      when:
        - firewalld_check.rc == 0
        - firewalld_status.stdout == "active"

    - name: Display firewall open ports
      debug:
        msg: "{{ opened_ports.stdout }}"
      when:
        - firewalld_check.rc == 0
        - firewalld_status.stdout == "active"

    - name: Firewall not installed or not active
      debug:
        msg: "firewalld not installed or inactive — skipping port configuration."
      when:
        - firewalld_check.rc != 0 or firewalld_status.stdout != "active"
