---
- name: Pre-check tasks
  hosts: masters
  gather_facts: no

  tasks:
    - name: Ensure firewall allows necessary ports
      ansible.builtin.shell: |
        firewall-cmd --permanent --add-port=6443/tcp
        firewall-cmd --permanent --add-port=2379-2380/tcp
        firewall-cmd --permanent --add-port=10250-10252/tcp
        firewall-cmd --reload
